#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gtkspell3
Version  : 3.0.10
Release  : 10
URL      : https://sourceforge.net/projects/gtkspell/files/3.0.10/gtkspell3-3.0.10.tar.xz
Source0  : https://sourceforge.net/projects/gtkspell/files/3.0.10/gtkspell3-3.0.10.tar.xz
Summary  : Provides word-processor-style highlighting and replacement of misspelled words in a GtkTextView widget
Group    : Development/Tools
License  : GPL-2.0
Requires: gtkspell3-data = %{version}-%{release}
Requires: gtkspell3-lib = %{version}-%{release}
Requires: gtkspell3-license = %{version}-%{release}
Requires: gtkspell3-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : glibc-bin
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(enchant-2)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : vala
BuildRequires : vala-dev

%description
/* gtkspell - a spell-checking addon for GTK's TextView widget
*/
Introduction
------------
GtkSpell is a library which provides MSWord/MacOSX-style highlighting of
misspelled words in a GtkTextView widget. Right-clicking a misspelled word pops
up a menu of suggested replacements.

%package data
Summary: data components for the gtkspell3 package.
Group: Data

%description data
data components for the gtkspell3 package.


%package dev
Summary: dev components for the gtkspell3 package.
Group: Development
Requires: gtkspell3-lib = %{version}-%{release}
Requires: gtkspell3-data = %{version}-%{release}
Provides: gtkspell3-devel = %{version}-%{release}

%description dev
dev components for the gtkspell3 package.


%package doc
Summary: doc components for the gtkspell3 package.
Group: Documentation

%description doc
doc components for the gtkspell3 package.


%package lib
Summary: lib components for the gtkspell3 package.
Group: Libraries
Requires: gtkspell3-data = %{version}-%{release}
Requires: gtkspell3-license = %{version}-%{release}

%description lib
lib components for the gtkspell3 package.


%package license
Summary: license components for the gtkspell3 package.
Group: Default

%description license
license components for the gtkspell3 package.


%package locales
Summary: locales components for the gtkspell3 package.
Group: Default

%description locales
locales components for the gtkspell3 package.


%prep
%setup -q -n gtkspell3-3.0.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1548351881
%configure --disable-static --enable-vala=yes
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1548351881
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gtkspell3
cp COPYING %{buildroot}/usr/share/package-licenses/gtkspell3/COPYING
%make_install
%find_lang gtkspell3

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GtkSpell-3.0.typelib
/usr/share/gir-1.0/*.gir
/usr/share/vala/vapi/gtkspell3-3.0.deps
/usr/share/vala/vapi/gtkspell3-3.0.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/gtkspell-3.0/gtkspell/gtkspell.h
/usr/lib64/libgtkspell3-3.so
/usr/lib64/pkgconfig/gtkspell3-3.0.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/gtkspell3/annotation-glossary.html
/usr/share/gtk-doc/html/gtkspell3/api-index-full.html
/usr/share/gtk-doc/html/gtkspell3/ch02.html
/usr/share/gtk-doc/html/gtkspell3/chapter-tutorial.html
/usr/share/gtk-doc/html/gtkspell3/gtkspell3-gtkspell.html
/usr/share/gtk-doc/html/gtkspell3/gtkspell3.devhelp2
/usr/share/gtk-doc/html/gtkspell3/home.png
/usr/share/gtk-doc/html/gtkspell3/index.html
/usr/share/gtk-doc/html/gtkspell3/left-insensitive.png
/usr/share/gtk-doc/html/gtkspell3/left.png
/usr/share/gtk-doc/html/gtkspell3/object-tree.html
/usr/share/gtk-doc/html/gtkspell3/right-insensitive.png
/usr/share/gtk-doc/html/gtkspell3/right.png
/usr/share/gtk-doc/html/gtkspell3/style.css
/usr/share/gtk-doc/html/gtkspell3/tutorial-advanced.html
/usr/share/gtk-doc/html/gtkspell3/tutorial-bindings.html
/usr/share/gtk-doc/html/gtkspell3/tutorial-building.html
/usr/share/gtk-doc/html/gtkspell3/tutorial-lang.html
/usr/share/gtk-doc/html/gtkspell3/up-insensitive.png
/usr/share/gtk-doc/html/gtkspell3/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgtkspell3-3.so.0
/usr/lib64/libgtkspell3-3.so.0.2.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gtkspell3/COPYING

%files locales -f gtkspell3.lang
%defattr(-,root,root,-)

